### ISSUE TITLE
Selection bug when cursor is outside grid

### ISSUE THREAD

**Issue by Stencil04** [silevis/react-dyna-grid#24]
Bug appear when selecting cell. During selection when cursor is outside grid, console showing error: `CellMatrix.ts:59 Uncaught TypeError: Cannot read property 'idx' of undefined`
I attach a gif file
![bug2](https://user-images.githubusercontent.com/20155130/41159064-819ed0e8-6b2b-11e8-9a5e-11dc4c6e05a0.gif)

**Comment by vaalgrind** [comment]
Done.
